train_data_dir: /home/guests/projects/ukbb/cardiac/cardiac_segmentations/subjects
train_start_idx: 0
num_train: 1000
val_data_dir: /home/guests/projects/ukbb/cardiac/cardiac_segmentations/subjects
val_start_idx: 1500
num_val: 5
test_data_dir: /home/guests/projects/ukbb/cardiac/cardiac_segmentations/subjects
test_start_idx: 1600
num_test: 100
log_dir: /home/guests/nil_stolt/results/cardiac_imp_seg

params:
    initial_val: False
    pos_encoding: "none"  # nerf, none, gaussian
    side_length: [192, 192, -1, 1]
    max_epochs: 1201
    log_interval: 20
    val_interval: 40
    fine_tune_max_epochs: 2001  # Lightning is faster doing (2000 epochs x 1 batch) than (1 epoch x 2000 batches)
    fine_tune_log_interval: 500
    x_holdout_rate: 2  # Height
    y_holdout_rate: 2  # Width
    z_holdout_rate: 1  # Slices
    t_holdout_rate: 1  # Time
    rec_loss_weight: 0.1
    lr: 1e-4
    fine_tune_lr: 1e-4
    latent_reg: 1e-4
    weight_reg: 1e-4
    activation: "wire"  # periodic, relu, wire
    wire_omega_0: 10.0
    skip_connections: True
    input_coord_to_all_layers: False
