train_data_dir: /home/guests/projects/ukbb/cardiac/cardiac_segmentations/subjects
train_start_idx: 0
num_train: 1500
val_data_dir: /home/guests/projects/ukbb/cardiac/cardiac_segmentations/subjects
val_start_idx: 1500
num_val: 5
test_data_dir: /home/guests/projects/ukbb/cardiac/cardiac_segmentations/subjects
test_start_idx: 1505
num_test: 6
log_dir: /home/guests/nil/Implicit_segmentation/logs/4d

params:
    initial_val: True
    pos_encoding: "none"  # nerf, none, gaussian
    side_length: [192, 192, -1, 1]
    max_epochs: 401
    log_interval: 5
    val_interval: 20
    fine_tune_max_epochs: 2001  # Lightning is faster doing (2000 epochs x 1 batch) than (1 epoch x 2000 batches)
    fine_tune_log_interval: 500
    lr: 1e-4
    fine_tune_lr: 1e-4
    latent_reg: 1e-4
    weight_reg: 1e-4
    activation: "wire"  # periodic, relu, wire
    wire_omega_0: 40.0
    skip_connections: True
    input_coord_to_all_layers: False
